services:
  parakeet:
    image: ghcr.io/amcfague/wyoming-parakeet-wrapper:latest
    platform: linux/amd64
    ports:
      - "10300:10300"
      - "8000:8000"
    volumes:
      - parakeet-models:/models
    gpus: all
    restart: unless-stopped

volumes:
  parakeet-models:
